HATCHES_2K = {
    "Tailow (Gen 3)",
    "Machop (Gen 1)",
    "Igglybuff (Gen2)",
    "Togepi (Gen 2) (Already in 2km Eggs)",
    "Luvdisc (Gen 3)",
    "Bidoof (Gen 4)",
    "Whismur (Gen 3)",
    "Shellder (Gen 1)",
    "Starly (Gen 4)",
    "Spheal (Gen 3)",
    "Swinub (Gen 2)",
    "Rhyhorn (Gen 1)",
    "Kricketot (Gen 4)",
    "Elekid (Gen 2)",
    "Cleffa (Gen2)",
    "Poochyena (Gen3)",
    "Wailmer (Gen 3)",
    "Aron (Gen 3)",
    "Budew (Gen 4)",
    "Barboach (Gen 3)",
    "Swablu (Gen 3)",
    "Magby (Gen 2)"}

HATCHES_5K = {
    "Budew (Gen 4) (Temporarily in 2km Eggs until November 27th)",
    "Mudkip (Gen3)",
    "Eevee (Gen 1)",
    "Piplup (Gen 4)",
    "Treecko (Gen3)",
    "Turtwig (Gen 4)",
    "Lickitung (Gen 1)",
    "Lotad (Gen 3)",
    "Pineco (Gen2)",
    "Mantine (Gen2)",
    "Kabuto (Gen 1)",
    "Anorith (Gen3)",
    "Onix (Gen 1)",
    "Carvanha (Gen3)",
    "Scyther (Gen 1)",
    "Corphish (Gen 3)",
    "Baltoy (Gen 3)",
    "Shroomish (Gen3)",
    "Omanyte (Gen 1)",
    "Snorunt (Gen3)",
    "Tangela (Gen 1)",
    "Nosepass (Gen3)",
    "Girafarig (Gen2)",
    "Tyrogue (Gen2)",
    "Cacnea (Gen 3)",
    "Magby (Gen 2) (Temporarily in 2km Eggs until November 27th)",
    "Lileep (Gen 3)",
    "Chimchar (Gen 4)",
    "Shuckle (Gen2)",
    "Buneary (Gen 4)",
    "Smoochum (Gen2)",
    "Azurill (Gen3)",
    "Makuhita (Gen3)",
    "Torchic (Gen3)",
    "Elekid (Gen 2) (Temporarily in 2km Eggs until November 27th)",
    "Wingull (Gen 3)",
    "Numel (Gen3)"}

HATCHES_7K = {
    "Alolan Sandshrew",
    "Alolan Grimer",
    "Alolan Vulpix",
    "Alolan Meowth",
    "Chansey (Gen 1)",
    "Lapras (Gen 1)",
    "Snorlax (Gen 1)",
    "Wynaut (Gen 3) ",
    "Pichu (Gen 2)",
    "Alolan Geodude",
    "Alolan Diglett"}

HATCHES_10K = {
    "Shinx (Gen 4)",
    "Chimecho (Gen 3)",
    "Beldum (Gen 3)",
    "Feebas (Gen 3)",
    "Trapinch (Gen 3)",
    "Riolu (Gen 4)",
    "Chansey (Gen 1)",
    "Bagon (Gen 3)",
    "Mareep (Gen2)",
    "Snorlax (Gen 1)",
    "Larvitar (Gen2)",
    "Porygon (Gen 1) (Temporarily in 2km Eggs until November 27th)",
    "Dratini (Gen 1)",
    "Slakoth (Gen3)"}
