HATCHES_2K = {
    "Shellder",
    "Luvdisc",
    "Elekid",
    "Aron",
    "Igglybuff",
    "Machop",
    "Spheal",
    "Poochyena",
    "Swinub",
    "Swablu",
    "Togepi",
    "Wailmer",
    "Whismur",
    "Magby",
    "Bidoof",
    "Barboach",
    "Rhyhorn",
    "Tailow",
    "Starly",
    "Cleffa",
    "Budew",
    "Kricketot"}

HATCHES_5K = {
    "Corphish",
    "Baltoy",
    "Mantine",
    "Nosepass",
    "Torchic",
    "Turtwig",
    "Elekid",
    "Piplup",
    "Treecko",
    "Onix",
    "Makuhita",
    "Eevee",
    "Chimchar",
    "Girafarig",
    "Mudkip",
    "Cacnea",
    "Pineco",
    "Omanyte",
    "Lotad",
    "Snorunt",
    "Azurill",
    "Lileep",
    "Lickitung",
    "Tangela",
    "Shroomish",
    "Magby",
    "Numel",
    "Wingull",
    "Buneary",
    "Carvanha",
    "Kabuto",
    "Anorith",
    "Shuckle",
    "Smoochum",
    "Budew",
    "Scyther",
    "Tyrogue"}

HATCHES_7K = {
    "Alolan Meowth",
    "Pichu",
    "Wynaut",
    "Alolan Geodude",
    "Snorlax",
    "Chansey",
    "Alolan Diglett",
    "Alolan Vulpix",
    "Lapras",
    "Alolan Sandshrew",
    "Alolan Grimer"}

HATCHES_10K = {
    "Porygon",
    "Chimecho",
    "Slakoth",
    "Shinx",
    "Snorlax",
    "Bagon",
    "Dratini",
    "Chansey",
    "Feebas",
    "Mareep",
    "Beldum",
    "Riolu",
    "Trapinch",
    "Larvitar"}
