IMP_TERMS = {
    "Berry",
    "Raid",
    "Candy",
    "Gym",
    "Ball",
    "Pokeball",
    "Stardust",
    "Eggs",
    "Research",
    "Event",
    "Type",
    "Trade",
    "Pokemon",
    "Alolan",
    "Shiny",
    "Regional",
    "Team",
    "Generation"
}

DEF_IMP_TERM ={
    "Berry": "Berries are items that can be fed to Pokemon while catching for different bonuses",
    "Raid": "Raids are when you get together as a group to fight a strong pokémon in a gym for the chance to catch it.",
    "Candy": "Candy can be used to evolve or power up pokémon.",
    "Gym": "Gyms are the battling place in the game. You can attack gyms controlled by opposing teams or "
           "add your pokemon to ones controlled by your team.",
    "Ball": "Pokeballs are the item used to catch pokemon with the different types having different catch rates",
    "Stardust": "Stardust can be used to power up or trade pokémon and can be gained in many ways",
    "Events": "Pokémon Go often hosts special events with bonuses and increased spawn rates for certain pokémon.",
    "Eggs": "Eggs contain Pokémon and can be hatched after walking the associated distance.",
    "Research": "Research are tasks that when completed give rewards",
    "Trade": "Trading is when you and a friend swap pokemon.",
    "Type": "Every pokemon has one or two types. When battling, certain types have advantages over other types, "
            "such as Water having an advantage over Fire.",
    "Pokemon": "Pokemon is short for pocket monsters and they are the cute creatures that you "
               "collect, battle and trade.",
    "Alolan": "Alolan pokemon are ones that resemble a pokemon but they have a different typing and a different design",
    "Shiny": "Shiny pokemon are the exact same as regular ones but they have a different coloring",
    "Regional": "Regional pokemon are only availible in certain regions of the world such as Tauras the bull pokemon "
                "only availible in North America",
    "Team": "There are three teams, Mystic, Instinct and Valor, only one team can control a gym at one time and the "
            "other teams must fight the gym to regain control",
    "Generation": "The pokemon added with each new installment in the main series games are a part of a different generation"
}

BERRY = [
    "There are currently 5 different types of berries: Razz Berry, Nanab Berry, Pinap Berry, "
    "Golden Razz Berry and Silver Pinap Berry.",
    "The berries are named after real fruits, namely the rasberry, banana and pineapple.",
    "The Razz Berry increases a pokémon's catch rate.",
    "The Nanab Berry makes a pokémon less erratic.",
    "Fun fact: Only the Razz Berry was available at launch. The other berries weren't added until later."
]

RAID = [
    "Raids are when you get together as a group to fight a strong pokémon in a gym.",
    "The reward for winning a raid is a chance to catch the pokémon as well as many other items.",
    "There are five levels of raids with level 5 being battles against legendary pokémon.",
    "Higher level raids give better rewards but require more people to defeat.",
    "A level 1 raid can be defeated by any trainer alone, but a level 5 raid requires at least 5 players.",
    "Raid bosses generally change about every month."
]

CANDY = [
    "Candy can be used to evolve pokémon.",
    "Candy is obtained every time a pokémon is caught, hatched, transferred or traded.",
    "The amount of candy you get in a trade is based on the distance between the catch locations of "
    "the two traded pokémon."
]

GYM = [
    "The Gym system has been reworked many times in attempt to make the game more fair.",
    "The gym can be controlled by any one of the three teams.",
    "If the gym is controlled by an opposing team, you can battle it to regain control.",
    "The longer you are in control of the gym, the more in game currency you can get.",
    "Fun fact: The gyms used to allow 10 pokémon to defend it, but now only allow 6 to increase transitions."]

BALL = [
    "There are three main types of balls: Poké ball, Great ball and Ultra ball.",
    "Each type ball has an incrementally better catch rate, ranking Poké balls as the lowest catch rate and "
    "Ultra balls as the highest catch rate.",
    "When you win a raid, you are given a certain number of Premier balls to catch the defeated pokémon. "
    "These disappear after the raid.",
    "Fun fact: You can see which pokéball was used to catch the specific pokémon on it's detail page."
]

STARDUST = [
    "Stardust can be used to power a pokémon.",
    "Stardust is gained by catching pokémon.",
    "You can use a Star Piece to double the amount of stardust you will earn for 30 minutes.",
    "Stardust must also be used to make trades."
]

EGGS = [
    "There are four types of eggs: 2km, 5km, 7km, 10km eggs.",
    "Each egg can be hatched after walking the associated distance.",
    "Rarer pokémon can be hatched from longer distance eggs.",
    "More candy and XP is obtained from longer distance eggs.",
    "7k eggs can only be obtained by opening gifts sent by friends, and contain unique pokémon such as Alolan or reqionals, which cannot be caught in the wild."
]

RESEARCH = [
    "There are two types of research to help Professor Willow with: Field Research and Special Research.",
    "Research tasks can be found by spinning pokéstops",
    "Fun Fact: everyone who spins a certain stop will get the same research task, so share the love for those chansey quests.",
    "Special research contains 7 steps with three tasks at each step with a final reward of catching a unique pokemon that can not be caught otherwise"
]

EVENT = [
    "Pokémon Go often hosts special events with bonuses and increased spawn rates for certain pokémon.",
    "Sometimes, events can be earned by meeting certain goals set by Niantic.",
    "Fun fact: Every summer there's a water festival event, which increased spawn rates of water pokémon."
]

TYPE = [
    "Every pokémon has one or two types associated with it.",
    "There are 18 different types, including Fire, Grass, Rock, and Fairy.",
    "When battling, certain types have advantages over other types, such as Water having an advantage over Fire.",
    "After a certain number of pokémon of a type is caught, you get a catch-bonus for those types of pokémons.",
    "Fun fact: Pokémon of certain types are boosted in strength depending on the weather."
]

TRADING = [
    "You can trade pokemon with friends and it's stats will be randomized so you can hope to get a better one",
    "When you trade, you have a chance to get a lucky pokemon which costs half stardust to power up!",
    "Trading gives you up to 3 candy based on how far apart the catch location of the pokemon being traded is"
]

GENERATION = [
    "Generations are released into pokemon go about once a year",
    "When a new generation is released into the game it usually released slowly with a few pokemon at at time to keep up excitment",
    'There are currently 4 generations in pokemon go'
]

POKEMON_TYPES = [
    "electric",
    "psychic",
    "water",
    "grass",
    "rock",
    "dragon",
    "fighting",
    "steel",
    "dark",
    "ghost",
    "bug",
    "ice",
    "fairy",
    "flying",
    "fire",
    "ground",
    "normal",
    "poison",
]

TEAMS = {
    "Mystic",
    "Instinct",
    "Valor",
    "Rocket"
}

TYPES = {
    "ground",
    "psychic",
    "fire",
    "ice",
    "flying",
    "steel",
    "fight",
    "bug",
    "dark",
    "normal",
    "water",
    "fairy",
    "poison",
    "dragon",
    "ghost",
    "electric",
    "rock",
    "grass"
}

ALL_POKEMON = {
    "Alakazam",
    "Sableye",
    "Treecko",
    "Gardevoir",
    "Turtwig",
    "Cradily",
    "Snorunt",
    "Wooper",
    "Aerodactyl",
    "Xatu",
    "Latios",
    "Starmie",
    "Meganium",
    "Bagon",
    "Mew",
    "Sneasel",
    "Togepi",
    "Porygon2",
    "Riolu",
    "Pidgeotto",
    "Barboach",
    "Dunsparce",
    "Murkrow",
    "Mantine",
    "Kricketot",
    "Seadra",
    "Granbull",
    "Ariados",
    "Chinchou",
    "Chimecho",
    "Togekiss",
    "Rapidash",
    "Golem",
    "Poliwag",
    "Rayquaza",
    "Charmander",
    "Sudowoodo",
    "Golduck",
    "Zangoose",
    "Gengar",
    "Mismagius",
    "Melmetal",
    "Sentret",
    "Skarmory",
    "Jynx",
    "Chatot",
    "Raikou",
    "Marowak",
    "Tyrogue",
    "Kyogre",
    "Bayleef",
    "Combusken",
    "Piloswine",
    "Ursaring",
    "Omastar",
    "Weavile",
    "Grotle",
    "Surskit",
    "Sceptile",
    "Duskull",
    "Shuckle",
    "Tentacool",
    "Swampert",
    "Unown",
    "Metagross",
    "Gligar",
    "Sunflora",
    "Electabuzz",
    "Suicune",
    "Feebas",
    "Gloom",
    "Abra",
    "Smoochum",
    "Honchkrow",
    "Magneton",
    "Nosepass",
    "Skiploom",
    "Hitmonlee",
    "Dustox",
    "Milotic",
    "Omanyte",
    "Shellder",
    "Hoppip",
    "Lopunny",
    "Delibird",
    "Hoothoot",
    "Chikorita",
    "Magby",
    "Slowpoke",
    "Spheal",
    "Oddish",
    "Graveler",
    "Kingler",
    "Swalot",
    "Mewtwo",
    "Ninetales",
    "Plusle",
    "Umbreon",
    "Qwilfish",
    "Rhyperior",
    "Luxray",
    "Lotad",
    "Regirock",
    "Ralts",
    "Cloyster",
    "Minun",
    "Makuhita",
    "Spearow",
    "Lucario",
    "Snubbull",
    "Taillow",
    "Weepinbell",
    "Shuppet",
    "Victreebel",
    "Flaaffy",
    "Zigzagoon",
    "Drifloon",
    "Clefairy",
    "Wobbuffet",
    "Cyndaquil",
    "Numel",
    "Cleffa",
    "Aipom",
    "Phanpy",
    "Rattata",
    "Poliwhirl",
    "Articuno",
    "Kirlia",
    "Scizor",
    "Poliwrath",
    "Slowbro",
    "Skitty",
    "Gliscor",
    "Jumpluff",
    "Porygon",
    "Nidoking",
    "Linoone",
    "Crawdaunt",
    "Budew",
    "Golbat",
    "Ekans",
    "Wigglytuff",
    "Pichu",
    "Monferno",
    "Wailmer",
    "Dragonite",
    "Flygon",
    "Starly",
    "Doduo",
    "Spoink",
    "Steelix",
    "Magmar",
    "Kangaskhan",
    "Blaziken",
    "Cubone",
    "Banette",
    "Aggron",
    "Exeggcute",
    "Groudon",
    "Haunter",
    "Charizard",
    "Elekid",
    "Pikachu",
    "Beldum",
    "Whismur",
    "Donphan",
    "Luxio",
    "Venusaur",
    "Snorlax",
    "Machoke",
    "Solrock",
    "Claydol",
    "Delcatty",
    "Bibarel",
    "Vaporeon",
    "Furret",
    "Dragonair",
    "Hariyama",
    "Metapod",
    "Altaria",
    "Clefable",
    "Growlithe",
    "Sharpedo",
    "Infernape",
    "Registeel",
    "Whiscash",
    "Tropius",
    "Mightyena",
    "Giratina",
    "Misdreavus",
    "Absol",
    "Drifblim",
    "Masquerain",
    "Ditto",
    "Loudred",
    "Corsola",
    "Blissey",
    "Drowzee",
    "Vileplume",
    "Shroomish",
    "Spinda",
    "Gastly",
    "Slaking",
    "Spiritomb",
    "Miltank",
    "Wingull",
    "Butterfree",
    "Chimchar",
    "Persian",
    "Dugtrio",
    "Meditite",
    "Camerupt",
    "Vigoroth",
    "Nidoqueen",
    "Mawile",
    "Ivysaur",
    "Piplup",
    "Ledyba",
    "Lickilicky",
    "Flareon",
    "Eevee",
    "Igglybuff",
    "Fearow",
    "Gulpin",
    "Kabuto",
    "Magmortar",
    "Porygon-Z",
    "Meowth",
    "Poochyena",
    "Hypno",
    "Aron",
    "Lunatone",
    "Pineco",
    "Squirtle",
    "Illumise",
    "Roselia",
    "Torkoal",
    "Onix",
    "Marshtomp",
    "Geodude",
    "Houndoom",
    "Charmeleon",
    "Primeape",
    "Buneary",
    "Nidorino",
    "Rhyhorn",
    "Arbok",
    "Venomoth",
    "Slugma",
    "Sandslash",
    "Deoxys",
    "Beautifly",
    "Celebi",
    "Dusclops",
    "Togetic",
    "Medicham",
    "Raticate",
    "Silcoon",
    "Dusknoir",
    "Nidoran",
    "Carnivine",
    "Wailord",
    "Bidoof",
    "Moltres",
    "Metang",
    "Swellow",
    "Houndour",
    "Voltorb",
    "Machamp",
    "Teddiursa",
    "Cacnea",
    "Seel",
    "Lanturn",
    "Tyranitar",
    "Jigglypuff",
    "Mareep",
    "Spinarak",
    "Vibrava",
    "Relicanth",
    "Castform",
    "Bellsprout",
    "Electivire",
    "Mankey",
    "Pinsir",
    "Ludicolo",
    "Ponyta",
    "Larvitar",
    "Armaldo",
    "Pidgeot",
    "Carvanha",
    "Croconaw",
    "Seedot",
    "Heracross",
    "Quagsire",
    "Baltoy",
    "Glalie",
    "Nidorina",
    "Mudkip",
    "Lombre",
    "Salamence",
    "Wurmple",
    "Lapras",
    "Diglett",
    "Feraligatr",
    "Seviper",
    "Politoed",
    "Sealeo",
    "Luvdisc",
    "Meltan",
    "Totodile",
    "Pupitar",
    "Lickitung",
    "Sandshrew",
    "Cascoon",
    "Walrein",
    "Volbeat",
    "Yanmega",
    "Slowking",
    "Wynaut",
    "Magnemite",
    "Dodrio",
    "Skuntank",
    "Forretress",
    "Kabutops",
    "Staryu",
    "Buizel",
    "Koffing",
    "Staraptor",
    "Shelgon",
    "Ledian",
    "Cacturne",
    "Magikarp",
    "Chansey",
    "Anorith",
    "Vulpix",
    "Floatzel",
    "Electrode",
    "Weedle",
    "Girafarig",
    "Bellossom",
    "Pidgey",
    "Shinx",
    "Tauros",
    "Bulbasaur",
    "Kadabra",
    "Seaking",
    "Goldeen",
    "Marill",
    "Ho-Oh",
    "Grovyle",
    "Gyarados",
    "Magcargo",
    "Breloom",
    "Dratini",
    "Horsea",
    "Mr. Mime",
    "Nuzleaf",
    "Rhydon",
    "Sunkern",
    "Raichu",
    "Hitmontop",
    "Nincada",
    "Paras",
    "Lileep",
    "Scyther",
    "Espeon",
    "Stunky",
    "Natu",
    "Weezing",
    "Empoleon",
    "Grimer",
    "Torchic",
    "Grumpig",
    "Kingdra",
    "Typhlosion",
    "Tentacruel",
    "Corphish",
    "Ninjask",
    "Shedinja",
    "Staravia",
    "Trapinch",
    "Caterpie",
    "Beedrill",
    "Machop",
    "Exploud",
    "Nidoran",
    "Zubat",
    "Parasect",
    "Venonat",
    "Blastoise",
    "Entei",
    "Remoraid",
    "Manectric",
    "Prinplup",
    "Pachirisu",
    "Azumarill",
    "Torterra",
    "Regice",
    "Slakoth",
    "Muk",
    "Electrike",
    "Wartortle",
    "Farfetch'd",
    "Lugia",
    "Latias",
    "Exeggutor",
    "Shiftry",
    "Jolteon",
    "Kakuna",
    "Arcanine",
    "Ampharos",
    "Stantler",
    "Swinub",
    "Zapdos",
    "Azurill",
    "Krabby",
    "Pelipper",
    "Psyduck",
    "Crobat",
    "Dewgong",
    "Hitmonchan",
    "Yanma",
    "Swablu",
    "Noctowl",
    "Kricketune",
    "Lairon",
    "Quilava",
    "Tangela",
    "Octillery",
    "Cranidos",
    "Gallade",
    "Garchomp",
    "Skorupi",
    "Bastiodon",
    "Mantyke",
    "Smeargle",
    "Uxie",
    "Toxicroak",
    "Shaymin",
    "Clamperl",
    "Gorebyss",
    "Bronzong",
    "Rampardos",
    "Happiny",
    "Leafeon",
    "Glaceon",
    "Regigigas",
    "Phione",
    "Manaphy",
    "Magnezone",
    "Darkrai",
    "Drapion",
    "Arceus",
    "Cresselia",
    "Snover",
    "Glameow",
    "Finneon",
    "Shieldon",
    "Azelf",
    "Gible",
    "Heatran",
    "Dialga",
    "Huntail",
    "Ambipom",
    "Rotom",
    "Vespiquen",
    "Purugly",
    "Bonsly",
    "Hippopotas",
    "Hippowdon",
    "Probopass",
    "Wormadam",
    "Croagunk",
    "Froslass",
    "Mothim",
    "Jirachi",
    "Combee",
    "Abomasnow",
    "Shellos",
    "Palkia",
    "Gastrodon",
    "Roserade",
    "Munchlax",
    "Lumineon",
    "Mamoswine",
    "Mesprit",
    "Chingling",
    "Tangrowth",
    "Cherubi",
    "Burmy",
    "Gabite",
    "Cherrim",
    "Bronzor",
    "Kecleon",
    "Mime Jr."
}