HATCHES_2K = {
    "Barboach (Gen 3)",
    "Aron (Gen 3)",
    "Igglybuff (Gen2)",
    "Magby (Gen 2)",
    "Starly (Gen 4)",
    "Bidoof (Gen 4)",
    "Tailow (Gen 3)",
    "Whismur (Gen 3)",
    "Wailmer (Gen 3)",
    "Shellder (Gen 1)",
    "Spheal (Gen 3)",
    "Cleffa (Gen2)",
    "Kricketot (Gen 4)",
    "Rhyhorn (Gen 1)",
    "Swablu (Gen 3)",
    "Elekid (Gen 2)",
    "Togepi (Gen 2) (Already in 2km Eggs)",
    "Swinub (Gen 2)",
    "Machop (Gen 1)",
    "Luvdisc (Gen 3)",
    "Budew (Gen 4)",
    "Poochyena (Gen3)"}

HATCHES_5K = {
    "Onix (Gen 1)",
    "Lileep (Gen 3)",
    "Lickitung (Gen 1)",
    "Carvanha (Gen3)",
    "Cacnea (Gen 3)",
    "Budew (Gen 4) (Temporarily in 2km Eggs until November 27th)",
    "Treecko (Gen3)",
    "Smoochum (Gen2)",
    "Magby (Gen 2) (Temporarily in 2km Eggs until November 27th)",
    "Numel (Gen3)",
    "Mantine (Gen2)",
    "Kabuto (Gen 1)",
    "Tangela (Gen 1)",
    "Omanyte (Gen 1)",
    "Shroomish (Gen3)",
    "Baltoy (Gen 3)",
    "Torchic (Gen3)",
    "Mudkip (Gen3)",
    "Eevee (Gen 1)",
    "Chimchar (Gen 4)",
    "Elekid (Gen 2) (Temporarily in 2km Eggs until November 27th)",
    "Piplup (Gen 4)",
    "Nosepass (Gen3)",
    "Makuhita (Gen3)",
    "Turtwig (Gen 4)",
    "Girafarig (Gen2)",
    "Snorunt (Gen3)",
    "Tyrogue (Gen2)",
    "Scyther (Gen 1)",
    "Pineco (Gen2)",
    "Wingull (Gen 3)",
    "Buneary (Gen 4)",
    "Corphish (Gen 3)",
    "Shuckle (Gen2)",
    "Lotad (Gen 3)",
    "Azurill (Gen3)",
    "Anorith (Gen3)"}

HATCHES_7K = {
    "Snorlax (Gen 1)",
    "Alolan Vulpix",
    "Lapras (Gen 1)",
    "Alolan Sandshrew",
    "Pichu (Gen 2)",
    "Alolan Geodude",
    "Wynaut (Gen 3) ",
    "Alolan Meowth",
    "Alolan Diglett",
    "Alolan Grimer",
    "Chansey (Gen 1)"}

HATCHES_10K = {
    "Larvitar (Gen2)",
    "Beldum (Gen 3)",
    "Porygon (Gen 1) (Temporarily in 2km Eggs until November 27th)",
    "Snorlax (Gen 1)",
    "Chansey (Gen 1)",
    "Trapinch (Gen 3)",
    "Chimecho (Gen 3)",
    "Riolu (Gen 4)",
    "Shinx (Gen 4)",
    "Slakoth (Gen3)",
    "Dratini (Gen 1)",
    "Feebas (Gen 3)",
    "Bagon (Gen 3)",
    "Mareep (Gen2)"}
